extends:
  - './.eslintrc.yml'
  - plugin:import/typescript
  - next
  - next/core-web-vitals

overrides:
  - files:
      - '*.ts'
      - '*.tsx'
    rules:
      import/no-unresolved: off
      import/order:
        - error
        - newlines-between: always
          groups:
            - builtin
            - external
            - internal
            - [parent, sibling, index]
          alphabetize:
            order: 'asc'
          pathGroups:
            - pattern: '{@front/**}'
              group: internal
              position: before
          pathGroupsExcludedImportTypes:
            - builtin
