root: true

parser: '@typescript-eslint/parser'

parserOptions:
  project: './tsconfig.base.json'

plugins:
  - '@nrwl/nx'
  - '@typescript-eslint'
  - prettier
  - jest

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - plugin:jest/recommended
  - plugin:jest/style

overrides:
  - files:
      - '*.ts'
      - '*.tsx'
    extends:
      - plugin:@nrwl/nx/typescript
    rules:
      '@typescript-eslint/explicit-function-return-type': off
      '@typescript-eslint/explicit-member-accessibility': off
      '@typescript-eslint/indent': off
      '@typescript-eslint/member-delimiter-style': off
      '@typescript-eslint/no-explicit-any':
        - error
      '@typescript-eslint/no-var-requires': off
      '@typescript-eslint/no-use-before-define': off
      '@typescript-eslint/no-unused-vars':
        - error
        - argsIgnorePattern: '^_'

  - files:
      - '*.js'
      - '*.jsx'
    extends:
      - plugin:@nrwl/nx/javascript
    rules: {}
