root: true

parser: '@typescript-eslint/parser'

parserOptions:
  project: './apps/front/tsconfig.json'

plugins:
  - '@typescript-eslint'
  - prettier
  - jest
  - jest-dom

extends:
  - plugin:@nrwl/nx/react-typescript
  - next
  - next/core-web-vitals
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:jest/recommended
  - plugin:jest/style
  - plugin:jest-dom/recommended

env:
  es6: true
  browser: true
  jest: true
  node: true

settings:
  react:
    version: detect

ignorePatterns:
  - '!**/*.ts'
  - '!**/*.tsx'
  - '**/*.js'

overrides:
  - files:
      - '*.ts'
      - '*.tsx'
    rules:
      '@next/next/no-html-link-for-pages':
        - error
        - apps/front/pages
      '@typescript-eslint/explicit-function-return-type': off
      '@typescript-eslint/explicit-member-accessibility': off
      '@typescript-eslint/indent': off
      '@typescript-eslint/member-delimiter-style': off
      '@typescript-eslint/no-explicit-any': off
      '@typescript-eslint/no-var-requires': off
      '@typescript-eslint/no-use-before-define': off
      '@typescript-eslint/no-unused-vars':
        - error
        - argsIgnorePattern: '^_'
      import/no-unresolved: off
      import/order:
        - error
        - newlines-between: always
          groups:
            - builtin
            - external
            - internal
            - [parent, sibling, index]
          alphabetize:
            order: 'asc'
          pathGroups:
            - pattern: '{@api/**,@front/**,@type/**}'
              group: internal
              position: before
          pathGroupsExcludedImportTypes:
            - builtin
      no-console:
        - error
        - allow: [warn, error]
      react/react-in-jsx-scope: off
      react/display-name: off
      react/prop-types: off
      jest/expect-expect:
        - error
        - assertFunctionNames:
            - expect
            - expect*
            - waitForElementToBeRemoved
            - screen.findBy*
