name: generating jest badges

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true

on:
  push:
    branches:
      - master

jobs:
  generating-jest-badges:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
            main-branch-name: 'master'

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.node-version'
          cache: 'yarn'

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Starting nx cloud CI
        run: yarn nx-cloud start-ci-run

      - name: Tests
        run: yarn nx run-many --target=test --all --parallel --max-parallel=3 --codeCoverage
        timeout-minutes: 10

      - name: Installing lcov
        run: sudo apt-get install -y lcov

      - name: Merge coverage
        run: find ./coverage -name "lcov.info" | awk '$0="-a "$0' | xargs lcov -o ./coverage/lcov.info

      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest
        with:
          branches: master
          coverage-summary-path: ./coverage/lcov.info

      - name: Stopping nx cloud CI
        run: yarn nx-cloud stop-all-agents
  
  agents:
    runs-on: ubuntu-latest
    name: Agent 1
    timeout-minutes: 60
    
    strategy:
      matrix:
        agent: [1, 2, 3]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.node-version'
          cache: 'yarn'
            
      - name: Installing dependencies
        run: yarn install --frozen-lockfile
      
      - name: Start Nx Agent ${{ matrix.agent }}
        run: yarn nx-cloud start-agent