on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
name: cypress tests
jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: caching next build
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Cypress run
        uses: cypress-io/github-action@v2
        env: |
          PORT=3000
          NEXT_PUBLIC_API_URL=https://rhf-mui-sandbox-backend.herokuapp.com
        with:
          build: npm run build
          start: npm start
