name: tests

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
            main-branch-name: 'master'

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.node-version'
          cache: 'yarn'

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Fetch sonar-scanner
        run: |
          curl https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.5.0.2216-linux.zip --create-dirs -o /tmp/sonar-scanner-cli/sonar-scanner-cli.zip
          mkdir ~/.sonar
          unzip -q /tmp/sonar-scanner-cli/sonar-scanner-cli.zip -d ~/.sonar/native-sonar-scanner

      - name: Starting nx cloud CI
        run: yarn nx-cloud start-ci-run

      - name: Linting
        run: yarn nx affected --target=lint --parallel --max-parallel=3
        timeout-minutes: 10

      - name: Tests
        run: yarn nx affected --target=test --parallel --max-parallel=3 --codeCoverage
        timeout-minutes: 10

      - name: Fix lcov paths for sonar
        run: |
          shopt -s globstar
          perl -i -p -e 's/(SF:).*(src\/.*)/$1$2/g;' coverage/**/lcov.info

      - name: Sonar scan
        run: yarn nx affected --target=sonar --parallel --max-parallel=3
        timeout-minutes: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          NX_CLOUD_DISTRIBUTED_EXECUTION: false

      - name: Stopping nx cloud CI
        run: yarn nx-cloud stop-all-agents
  
  agents:
    runs-on: ubuntu-latest
    name: Agent 1
    timeout-minutes: 60
    
    strategy:
      matrix:
        agent: [1, 2, 3]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.node-version'
          cache: 'yarn'
            
      - name: Installing dependencies
        run: yarn install --frozen-lockfile
      
      - name: Start Nx Agent ${{ matrix.agent }}
        run: yarn nx-cloud start-agent